package com.notrika.gympin.common.gateway.parsian.service;

import com.notrika.gympin.common.gateway.parsian.AutoGenerated.ClientSaleRequestData;
import com.notrika.gympin.common.gateway.parsian.AutoGenerated.SalePaymentRequest;
import com.notrika.gympin.common.gateway.parsian.AutoGenerated.SalePaymentRequestResponse;

public interface gatewayParsianService {
    SalePaymentRequestResponse salePaymentRequest(SalePaymentRequest param);
}
