package com.notrika.gympin.common.gateway.parsian.service;

import com.notrika.gympin.common.gateway.parsian.AutoGenerated.*;

public interface gatewayParsianService {
    ClientSaleResponseData salePaymentRequest(ClientSaleRequestData param);
    ClientConfirmResponseData confirmPaymentRequest(ClientConfirmRequestData param);
}
