//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.10 at 08:47:35 PM GMT+03:30 
//


package com.notrika.gympin.common.gateway.parsian.AutoGenerated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.notrika.gympin.common.gateway.parsian.AutoGenerated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.notrika.gympin.common.gateway.parsian.AutoGenerated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SalePaymentRequest }
     * 
     */
    public SalePaymentRequest createSalePaymentRequest() {
        return new SalePaymentRequest();
    }

    /**
     * Create an instance of {@link ClientSaleRequestData }
     * 
     */
    public ClientSaleRequestData createClientSaleRequestData() {
        return new ClientSaleRequestData();
    }

    /**
     * Create an instance of {@link SalePaymentRequestResponse }
     * 
     */
    public SalePaymentRequestResponse createSalePaymentRequestResponse() {
        return new SalePaymentRequestResponse();
    }

    /**
     * Create an instance of {@link ClientSaleResponseData }
     * 
     */
    public ClientSaleResponseData createClientSaleResponseData() {
        return new ClientSaleResponseData();
    }

    /**
     * Create an instance of {@link SalePaymentWithId }
     * 
     */
    public SalePaymentWithId createSalePaymentWithId() {
        return new SalePaymentWithId();
    }

    /**
     * Create an instance of {@link SalePaymentWithIdResponse }
     * 
     */
    public SalePaymentWithIdResponse createSalePaymentWithIdResponse() {
        return new SalePaymentWithIdResponse();
    }

    /**
     * Create an instance of {@link UDSalePaymentRequest }
     * 
     */
    public UDSalePaymentRequest createUDSalePaymentRequest() {
        return new UDSalePaymentRequest();
    }

    /**
     * Create an instance of {@link UDSalePaymentRequestResponse }
     * 
     */
    public UDSalePaymentRequestResponse createUDSalePaymentRequestResponse() {
        return new UDSalePaymentRequestResponse();
    }

    /**
     * Create an instance of {@link ClientPaymentResponseDataBase }
     * 
     */
    public ClientPaymentResponseDataBase createClientPaymentResponseDataBase() {
        return new ClientPaymentResponseDataBase();
    }

    /**
     * Create an instance of {@link SalePaymentWithDiscount }
     * 
     */
    public SalePaymentWithDiscount createSalePaymentWithDiscount() {
        return new SalePaymentWithDiscount();
    }

    /**
     * Create an instance of {@link ClientSaleDiscountRequestData }
     * 
     */
    public ClientSaleDiscountRequestData createClientSaleDiscountRequestData() {
        return new ClientSaleDiscountRequestData();
    }

    /**
     * Create an instance of {@link SalePaymentWithDiscountResponse }
     * 
     */
    public SalePaymentWithDiscountResponse createSalePaymentWithDiscountResponse() {
        return new SalePaymentWithDiscountResponse();
    }

    /**
     * Create an instance of {@link ClientPaymentRequestDataBase }
     * 
     */
    public ClientPaymentRequestDataBase createClientPaymentRequestDataBase() {
        return new ClientPaymentRequestDataBase();
    }

    /**
     * Create an instance of {@link ArrayOfProduct }
     * 
     */
    public ArrayOfProduct createArrayOfProduct() {
        return new ArrayOfProduct();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

}
