//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.10 at 09:35:52 PM GMT+03:30 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.notrika.gympin.common.gateway.parsian.AutoGenerated;
