package com.notrika.gympin.domain.gateways.parsian;


import com.notrika.gympin.common.gateway.parsian.AutoGenerated.ClientSaleRequestData;
import com.notrika.gympin.common.gateway.parsian.AutoGenerated.SalePaymentRequest;
import com.notrika.gympin.common.gateway.parsian.AutoGenerated.SalePaymentRequestResponse;
import com.notrika.gympin.common.gateway.parsian.service.gatewayParsianService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;
import org.springframework.stereotype.Service;
import org.springframework.ws.client.core.WebServiceTemplate;

@Service
public class ParsianGatewayServiceImpl implements gatewayParsianService {


    @Autowired
    private Jaxb2Marshaller marshaller;

    private WebServiceTemplate template;


    public SalePaymentRequestResponse salePaymentRequest(SalePaymentRequest param) {
        template = new WebServiceTemplate(marshaller);
        SalePaymentRequestResponse salePaymentRequest = (SalePaymentRequestResponse) template.marshalSendAndReceive("https://pec.shaparak.ir/NewIPGServices/Sale/SaleService.asmx", param);
        return salePaymentRequest;
    }

}
