package com.notrika.gympin.common.finance.gateway.service;

import com.notrika.gympin.common.finance.gateway.AutoGenerated.ClientConfirmRequestData;
import com.notrika.gympin.common.finance.gateway.AutoGenerated.ClientConfirmResponseData;
import com.notrika.gympin.common.finance.gateway.AutoGenerated.ClientSaleRequestData;
import com.notrika.gympin.common.finance.gateway.AutoGenerated.ClientSaleResponseData;
import com.notrika.gympin.common.finance.gateway.param.PersianGatewayCallbackParam;
import org.springframework.ui.Model;

import javax.servlet.http.HttpServletRequest;

public interface GatewayBankService {
    ClientSaleResponseData salePaymentRequest(ClientSaleRequestData param);
    ClientConfirmResponseData confirmPaymentRequest(ClientConfirmRequestData param);

    String callback(HttpServletRequest request, Model model, PersianGatewayCallbackParam param, String ref) throws Exception;
}
