export const PagesViewTypes = {

    CAROUSEL:{SIMPLE_LIST:"SIMPLE_LIST",INCREDIBLE_LIST:"INCREDIBLE_LIST",BUTTON_LIST:"BUTTON_LIST"},
    BANNER:{BANNER_FULL:"BANNER_FULL"},
    TEXT:{TITLE_MORE:"TITLE_MORE",SIMPLE_TITLE:"SIMPLE_TITLE"},
//childes
    BANNER_IMAGE:{xs:"xs",sm:"sm",md:"md"},
    QUERY_GYM:{SIMPLE_GYM:"SIMPLE_GYM"},
    QUERY_SUBSCRIBE:{SIMPLE_SUBSCRIBE:"SIMPLE_SUBSCRIBE"},
    QUERY_APPOINTMENT:{SIMPLE_APPOINTMENT:"SIMPLE_APPOINTMENT"},
    QUERY_COUNSELING:{SIMPLE_COUNSELING:"SIMPLE_COUNSELING"},
    CAROUSEL_BUTTON:{SIMPLE_SPORT_CAT:"SIMPLE_SPORT_CAT",NEW_SPORT_CAT:"NEW_SPORT_CAT"}
}
