export const serviceEnum = {
    "AccountControllerImpl.refreshToken": "نوسازی توکن",
    "QrCodeControllerImpl.getCode": "دریافت qr کد جدید",
    "PurchasedSubscribeControllerImpl.addEnterToSubscribe": "ثبت ورود برای عضویت",
    "InvoiceControllerImpl.userCheckout": "پرداخت سبد خرید",
    "InvoiceControllerImpl.addBuyable": "افزودن به سبد خرید",
    "PurchasedSubscribeControllerImpl.acceptEnterRequested": "تایید درخواست ورود کاربر",
    "PurchasedSubscribeControllerImpl.enterRequest": "ثبت درخواست ورود به مجموعه",
    "FinanceIncreaseUserDepositControllerImpl.requestIncreaseUserDeposits": "درخواست افزایش شارژ کاربر",
    "TicketBuyableControllerImpl.setTicketBeneficiary": "ثبت ذی نفع برای بلیط",
    "PlacePersonnelControllerImpl.updatePersonnelCommissionFee": "ویرایش کمیسیون",
    "PlacePersonnelControllerImpl.addRole": "ثبت نقش برای پرسنل مرکز",
    "FinanceIncreaseUserDepositControllerImpl.confirmIncreaseRequest": "تایید افزایش شارژ کاربر",
    "FinanceIncreaseCorporateDepositControllerImpl.confirmIncreaseRequest": "تایید افزایش شارژ شرکت",
    "ApplicationConfigControllerImpl.WebAppSplash": "دریافت اطلاعات اولیه اپلیکیشن وب",
    "AccountControllerImpl.loginUser": "ورود کاربر",
    "AccountControllerImpl.sendSms": "دریافت پیامک ورود",
    "SupportControllerImpl.addMessageToSupport": "افزودن پیام به پشتیبانی",
    "TicketSubscribeControllerImpl.deleteSubscribeActiveTimes": "حذف زمان فعالیت  از عضویت",
    "ApplicationConfigControllerImpl.MasterSplash": "دریافت اطلاعات اولیه اپلیکیشن مراکز",
    "ApplicationConfigControllerImpl.CorporateSplash": "دریافت اطلاعات اولیه اپلیکیشن سازمان ها",
    "AccountControllerImpl.RequestRegisterPlace": "درخواست عضویت مرکز",
    "PlacePersonnelControllerImpl.updatePersonnelAccess": "ویرایش دسترسی پرسنل به بلیط",
    "PlacePersonnelControllerImpl.updatePersonnelBuyableAccess": "ویرایش دسترسی پرسنل به بخش ها",
    "InvoiceControllerImpl.changeInvoiceBuyableCount": "تغییر تعداد بلیط در سبد خرید یا فاکتور",
    "AccountControllerImpl.registerByInviteCode": "ثبت نام با کد معرف",
    "SmsControllerImpl.changeSmsStatus": "تغییر وضعیت پیامک",
    "UserControllerImpl.updateUserRole": "تغییر نقش کاربر",
    "TicketSubscribeControllerImpl.addSport": "افزودن ورزش به عضویت",
    "PlaceControllerImpl.addMultimediaList": "افزودن تصویر به مجموعه",
    "PlaceControllerImpl.changeStatus": "تغییر وضعیت مرکز",
    "CorporatePersonnelControllerImpl.addPersonnelCredit": "افزودن اعتبار به پرسنل",
    "CorporateControllerImpl.updateStepPayment": "بروز رسانی مرحله پرداخت",
    "InvoiceControllerImpl.changeStatus": "تغییر وضعیت فاکتور",
    "InvoiceControllerImpl.checkout": "پرداخت فاکتور",
    "PurchasedSubscribeControllerImpl.increaseExpireDate": "افزایش تاریخ انقضای بلیط",
    "CorporateControllerImpl.updateStatus": "سازمان تغییر وضعیت",
    "TicketSubscribeControllerImpl.changeTicketSubscribeStatus": "تغییر وضعیت عضویت",
    "UserControllerImpl.updateUserAvatar": "تغییر تصویر کاربر",
    "CorporateControllerImpl.deleteCorporateGroup": "حذف کروه پرسنل سازمان",
    "CorporatePersonnelControllerImpl.addToAllPersonnelCredit": "افزایش اعتبار به همه پرسنل",
    "CorporateControllerImpl.addCorporateGroup": "افزودن گروه پرسنل سازمان",
    "FinanceIncreaseCorporateDepositControllerImpl.requestIncreaseCorporateDeposits": "درخواست افزایش اعتبار کاربر",
    "CorporateControllerImpl.updateLogo": "تغییر لوگو شرکت",
    "FinanceSettlementUserDepositControllerImpl.confirmSettlementRequest": "تایید درخواست پرداخت",
    "TicketSubscribeControllerImpl.deleteSport": "حذف ورزش",
    "PurchasedSubscribeControllerImpl.updateStatus": "تغییر وضعیت بلیط",
    "InvoiceControllerImpl.deleteBuyable": "حذف بلیط",
    "PurchasedSubscribeControllerImpl.addEntryMessage": "افزودن پیام به بلیط",
    "UserControllerImpl.addUserRole": "افزودن نقش به کاربر",
    "UserControllerImpl.removeUserRole": "حذف نقش کاربر",
    "UserControllerImpl.couchQuery": "دریافت مربیان",
    "PlaceControllerImpl.deleteMultimedia": "حذف تصویر",
    "TicketCourseControllerImpl.addCourseActiveTimes": "افزودن زمان به کلاس",
    "TicketCourseControllerImpl.addSport": "افزودن ورزش",
    "TicketCourseControllerImpl.deleteSport": "خذف ورزش",
    "TicketCourseControllerImpl.changeTicketCourseStatus": "تغببر وضعیت کلاس",
    "TicketCourseControllerImpl.addCoach": "افزودن مربی",
    "TicketCourseControllerImpl.deleteCoach": "حذف مربی",
    "PurchasedCourseControllerImpl.addEnterToCourse": "افزودن ورود به بلیط",
    "PurchasedCourseControllerImpl.enterRequest": "ثبت درخواست ورود",
    "PlacePersonnelControllerImpl.deleteRole": "خذف نقش پرسنل مجموعه",
    "AccountControllerImpl.RequestRegisterAdvice": "درخواست ثبت نام مجموعه",
    "PlaceControllerImpl.addMultimedia": "افزودن تصویر",
    "UserControllerImpl.SetUserSettings": "تغییر تنظیمات کاربر",
    "UserControllerImpl.updateUserStatus": "تغییر وضعیت کاربر",
    "ServiceControllerImpl.getUsersActive": "مشاهده کاربران فعال",
    "TicketSubscribeControllerImpl.deleteCoach": "حذف مربی از عضویت",
    "TicketSubscribeControllerImpl.addCoach": "افزودن مربی به عضویت",
    "AccountControllerImpl.RequestRegisterCorporate": "درخواست عضویت سازمان",
    "AccountControllerImpl.RequestPublicMessage": "پیام عمومی به جیم پین",
    "CorporatePersonnelControllerImpl.manualExpireUserCredit": "انقضای دستی",
    "InvoiceControllerImpl.getUserHowToPay": "مشاهده راه های پرداخت",
    "CorporateControllerImpl.getTotalIncreases": "مشاهده پرداخت تجمعی",
    "PlaceControllerImpl.updateOrder": "تقییر چیدمان مراکز صفحه اصلی",
    "NoteControllerImpl.query": "دریافت اطلاعات یاداشت ها",
    "SupportControllerImpl.query": "دریافت لیست پشتیبانی ها",
    "CorporateControllerImpl.getCorporateGroups": "دریافت گروه بندی شرکت",
    "FinanceSettlementUserDepositControllerImpl.query": "دریافت تسویه حساب ها",
    "TicketBuyableControllerImpl.getWanderers": "دریافت لیست بلیط های بدون ذینفع",
    "FinanceIncreaseCorporateDepositControllerImpl.query": "دریافت لیت افزاش شارژ های شرکت",
    "FinanceIncreaseUserDepositControllerImpl.query": "دریافت لیت افزاش شارژ های شخصی",
    "CorporateControllerImpl.getById": "دریافت اطلاعات شرکت",
    "InvoiceControllerImpl.query": "دریافت فاکتورهای پرداخت",
    "UserControllerImpl.query": "دریافت لیست کاربران",
    "LocationControllerImpl.query": "دریافت منطقه ها",
    "SportControllerImpl.query": "دریافت ورزش ها",
    "SettingControllerImpl.getAll": "دریافت تنظیمات",
    "CorporateControllerImpl.query": "دریافت لیست شرکت ها",
    "PlaceControllerImpl.getById": "دریافت اطلاعات پایه یک مرکز",
    "CorporateControllerImpl.updateContractType": "بروز رسانی اطلاعات قرارداد",
    "CorporatePersonnelControllerImpl.query": "دریافت پرسنل سازمان",
    "SmsControllerImpl.query": "دریافت لیست پیامک ها",
    "UserControllerImpl.getById": "دریافت اطلاعات یک کاربر",
    "UserControllerImpl.getMyInfo": "دریافت اطلاعات کاربری خود",
    "CorporateControllerImpl.updateDefaultExpireDuration": "بروز رسانی مدت پیشفرض انقضا",
    "CorporateControllerImpl.updateContractDate": "بروزرسانی اطلاعات قرارداد",
    "SmsControllerImpl.updatePattern": "بروزرسانی پترن پیامک",
    "TicketBuyableControllerImpl.query": "دریافت لیست بلیط ها",
    "SmsControllerImpl.addPattern": "افزودن پترن پیامک",
    "ArticleControllerImpl.updateArticleImage": "ویرایش تصویر مقاله",
    "CorporateControllerImpl.updateContract": "بروز رسانی قرارداد",
    "CorporatePersonnelControllerImpl.getCorporateByUser": "دریافت سازمان های یک کاربر",
    "PlaceControllerImpl.updateContract": "بروز رسانی قرارداد",
    "CorporatePersonnelControllerImpl.getById": "دریافت اطلاعات پرسنلی یک نفر",
    "GatewayControllerImpl.query": "دریافت راه های پرداخت",
    "CorporateControllerImpl.sendContractCode": "ارسال رمز فرارداد سازمان",
    "CorporateControllerImpl.signContract": "امضا قرارداد سازمان",
    "ServiceControllerImpl.query": "دریافت اطلاعات اجرای سرویس ها",
    "PlaceControllerImpl.sendContractCode": "ارسال رمز فرارداد مرکز ورزشی",
    "PlaceControllerImpl.signContract": "امضا قرارداد مرکز ورزشی",
    "UserControllerImpl.getUserSettings": "دریافت تنظیمات کاربر",
    "PlacePersonnelControllerImpl.getPersonnelByUser": "دریافت اطلاعات یک کارمند مرکز ورشی",
    "HomePageControllerImpl.getHome": "دربافت اطلاعات صفحه خانه",
    "CorporatePersonnelControllerImpl.delete": "حذف یک پرسنل سازمان",
    "ArticleControllerImpl.query": "دریافت لیست مقالات",
    "ArticleControllerImpl.getById": "دریافت یک مقاله",
    "GatewayApplicationControllerImpl.query": "دریافت لیست راه های پرداخت",
    "SuggestControllerImpl.query": "دریافت پیشنهادات پرداخت",
    "ServiceControllerImpl.deleteCorruptedItems": "حذف اطلاعات گزارشات مشکل دار",
    "PurchasedControllerImpl.query": "دریافت لیست بلیط های خریداری شده",
    "PlacePersonnelControllerImpl.getUserPlaceAccess": "دریافت دسترسی های کاربری",
    "CorporateControllerImpl.add": "افزودن سازمان",
    "CorporatePersonnelControllerImpl.add": "افزودن پرسنل سازمان",
    "UserControllerImpl.update": "بروز رسانی اطلاعات مشخصات کاربر",
    "UserControllerImpl.getUserStatuses": "بروز رسانی وضعیت کاربر",
    "UserRoleControllerImpl.getAllRoles": "دریافت لیست نقش ها",
    "SerialControllerImpl.query": "دریافت لیست فرایند ها",
    "HomePageControllerImpl.query": "دریافت لیست اطلاعات صفحه یا صفحات",
    "CorporatePersonnelControllerImpl.update": "بروز رسانی اطلاعات پرسنل سازمان",
    "SupportControllerImpl.getById": "دریافت اطلاعات یک پشتیبانی",
    "CorporateControllerImpl.getFinanceCorporate": "دریافت اطلاعات مالی شرکت",
    "SettingControllerImpl.UpdateAutoDiscount": "بروز رسانی دستی تخفیف ها",
    "SettingControllerImpl.DoMaximumDiscount": "اعمال بیشترین تخفیف",
    "SettingControllerImpl.SetAutoToAll": "فعال سازی تخفیف اتوماتیک برای همه",
    "PlaceControllerImpl.getMultimedias": "دریافت تصاویر مجموعه",
    "MultimediaCategoryControllerImpl.getById": "دریافت یک دسته بندی تصویر",
    "CorporatePersonnelControllerImpl.getCorporateOwnedByUser": "دریافت مراکز تحت مدیریت کاربر",
    "SupportControllerImpl.getCorporateSupportCount": "دریافت تعداد پشتیبانی های نخوانده",
    "CorporatePersonnelControllerImpl.addNWToAllPersonnelCredit": "اقزایش اعتبار غیر قابل برداشت برای پرسنل یک سازمان",
    "MultimediaControllerImpl.add": "افزودن تصویر",
    "PlaceAboutControllerImpl.update": "آپدیت درباره مجموعه",
    "TicketSubscribeControllerImpl.getById": "دریافت اصلاعات یک بلیط",
    "TicketSubscribeControllerImpl.getCoaches": "دریافت مربیان یک بلیط",
    "TicketSubscribeControllerImpl.getSports": "دریافت ورزش های یک بلیط",
    "TicketSubscribeControllerImpl.update": "آپدیت اطلاعات یک بلیط",
    "SportControllerImpl.getAll": "دریافت همه ورزش ها",
    "GiftCreditControllerImpl.query": "دریافت لیست هدایا",
    "UserControllerImpl.getMyCredits":"در یافت اعتبار های من",
    "GiftCreditControllerImpl.getByCode":"دریافت اطلاعات یک کارت هدیه",
    "GiftCreditControllerImpl.claimGift":"درخاست اعتبار یک هدیه",
    "InvoiceControllerImpl.getBasketByUserId":"دریافت اطلاعات سبد خرید",
    "PurchasedSubscribeControllerImpl.getEnterRequestedSubscribe":"دریافت اطلاعات درخواست ورود کاربران",
    "PurchasedSubscribeControllerImpl.getUserEnteredSubscribe":"دریافت اطلاعات کاربران در مجموعه",
    "TransactionUserControllerImpl.query":"دریافت تراکنش های کاربر",
    "FinanceIncreaseCorporateDepositControllerImpl.requestIncreaseCorporateDepositsDraft":"ایجاد درخواست افزایش اعتبار مجموعه",
    "PurchasedSubscribeControllerImpl.query":"دریافت بلیط های خریداری شده",
    "ReportControllerImpl.useCorporateCharge":"دریافت گزارش شارژ مصرف شده",
    "PlaceGymControllerImpl.query":"دریافت مراکز ورزشی",
    "PlaceGymControllerImpl.getById":"دریافت اطلاعات یک مرکز",
    "CorporateControllerImpl.update":"بروز رسانی اطلاعات یک شرکت",
    "PlaceCateringControllerImpl.query":"دریافت لیست کیترینگ ها",
    "TicketFoodMenuControllerImpl.getFoodMenuDates":"دریافت تاریخ های منو های یک کیترینگ",
    "TicketFoodMenuControllerImpl.query":"دریافت کیست منوی غذا ها",
    "SupportControllerImpl.add":"افزودن یک پیام پشتیبانی",
    "SupportControllerImpl.setMessagesRead":"خواندن یک پیام پشتیبانی",
    "PlaceGymControllerImpl.update":"بروز رسانی اطلاعات یک مجموعه",
    "PlaceOptionControllerImpl.getAll":"دریافت امکانات یک مجموعه",
    "PlaceGymControllerImpl.getMultimedias":"دریافت تصاویر یک مجموعه",
    "PlaceAboutControllerImpl.add":"اقزودن درباره به یک مجموعه",
    "OptionOfPlaceControllerImpl.add":"افزودن یک امکانات به مجموعه",
    "OptionOfPlaceControllerImpl.delete":"حذف یک امکانات از مجموعه",
    "PlaceSportControllerImpl.add":"افزودن یک ورزش به مجموعه",
    "TicketSubscribeControllerImpl.add":"اقزودن یک بلیط به مجموعه",
    "TicketSubscribeControllerImpl.delete":"حذف یک بلیط از مجموعه",
    "SupportControllerImpl.getByPlace":"دریافت پشتیبانی های یک مجموعه",
    "PlaceSportControllerImpl.delete":"حذف یک ورزش از یک مجموعه",
    "PlaceGymControllerImpl.deleteMultimedia":"حذف یکی از تصاویر مجموعه",
    "PlaceGymControllerImpl.addMultimedia":"افزودن تصاویر به یک مجموعه",
    "PurchasedSubscribeControllerImpl.getPlaceSubscribes":"دریافت بلیط های یک مجموعه",
    "PlaceGymControllerImpl.updateContract":"به روز رسانی اطلاعات قرارداد",
    "PlaceGymControllerImpl.sendContractCode":"ارسال کد تفاهم نامه",
    "PlaceGymControllerImpl.signContract":"امضای قرارداد",
    "PlaceGymControllerImpl.changeStatus":"تغییر وضعیت یک مجموعه",
    "PurchasedSubscribeControllerImpl.getPurchasedByKey":"دریافت یک بلیط خریداری شده با کد",
    "PlacePersonnelControllerImpl.add":"افزودن پرسنل مجموعه",
    "PlaceCommentControllerImpl.query":"دریافت نظرات یک مجموعه",
    "PlaceCommentControllerImpl.add":"افزودن کامنت به یک مجموعه",
    "UserControllerImpl.checkUsernameAvailable":"بررسی خالی بود نام کاربری",
    "InvoiceControllerImpl.addSubscribe":"افزودت ورزش به سبد خرید",
    "InvoiceControllerImpl.SmartisCheckOut":"پرداخت با اسمارتیز",
    "ServiceControllerImpl.getActiveUsersByCorporate":"دریافت گزارش کاربران فعال مجموعه",
    "TransactionPersonnelCreditControllerImpl.query":"دریافت تراکنش های اعتباری کارمندان",
    "TransactionCorporateControllerImpl.query":"دریافت تراکنش های سازمان",
    "PlaceCateringControllerImpl.getById":"دریافت اطلاعات یک کیترینگ",
    "PlacePersonnelControllerImpl.getUserPlaceBuyableAccess":"دریافت دسترسی یک پرسنل مجموعه ورزشی به بلیط ها",
    "TagControllerImpl.query":"دریافت لیست های یک تگ",
    "InvoiceControllerImpl.getById":"دریافت یک فاکتور",
    "UserControllerImpl.getUserCredits":"دریافت اعتبار های یک کاربر",
    "SerialControllerImpl.getBySerial":"دریافت اطلاعات یک سریال",
    "UserRoleControllerImpl.query":"دریافت لیست دسترسی های کاربران",
    "TagControllerImpl.getPlaceTags":"دربافت تگ های یک مجموعه",
    "TicketSubscribeControllerImpl.getTicketSubscribeDiscountHistory":"دریافت تاریخچه تخفیف های یک مجموعه",
    "ActiveTimesControllerImpl.getTicketActiveTimesByPlace":"دریافت ساعات فعالیت یک بلیط",
    "TicketSubscribeControllerImpl.getSubscribeActiveTimesByTicketSubscribe":"دریافت زمان های فعالیت یک بلیط",
    "PlaceGymControllerImpl.getBuyableByPlace":"دریافت فروشی های یک مجموعه",
    "PlaceGymControllerImpl.add":"افزودن یک مجموعه",
    "PlaceGymControllerImpl.getPlaceInviteCode":"دریافت کد عضویت مجموعه",
    "PlaceAboutControllerImpl.delete":"حذف یک قوانین مجموعه",
    "PlacePersonnelControllerImpl.getById":"دریافت اطلاعات یک کارمند",
    "ReportSettingsControllerImpl.getAll":"دریافت لیست تنضیمات گزارشات",
    "PurchasedSubscribeControllerImpl.getById":"دریافت اطلاعات یک بلیط پرداخت شده",
    "SerialControllerImpl.getById":"دریافت اطلاعات یک سریال",
    "SportControllerImpl.add":"افزودن یک ورزش",
    "TagControllerImpl.addToPlace":"افزودن یک تگ به مجموعه",
    "MultimediaCategoryControllerImpl.getAll":"دریافت دسته بندی های تصاویر",
    "MultimediaControllerImpl.query":"دریافت لیست تصاویر",
    "PlaceGymControllerImpl.addMultimediaList":"اقزودن لیستی از تصاویر",
    "NoteControllerImpl.add":"افزودن یک نت",
    "LinkControllerImpl.query":"دریافت لیست لینک ها",
    "LinkControllerImpl.add":"افزودن یک لینک",
    "LinkControllerImpl.getByCode":"دریافت یک لینک",
    "PurchasedSubscribeControllerImpl.exitRequest":"خروج از مجموعه ورزشی",
    "AffiliateControllerImpl.query":"دریافت همکاران در فروش",
    "SmsControllerImpl.getAllPaterns":"دریافت لیست پترن های پیامک",
    "SettingControllerImpl.update":"بروز رسانی تنظیمات",
    "TransactionIncomeControllerImpl.query":"دریافت درامد ها",
    "UserControllerImpl.getUserByUsername":"دریافت یک کاربر با نام کاربری",
    "PlacePersonnelControllerImpl.delete":"حذف یک پرسنل از مجموعه",
    "UserRoleControllerImpl.add":"افزودن نقش کاربری",
    "FinanceSettlementUserDepositControllerImpl.add":"درخواست تسویه حساب",
    "HomePageControllerImpl.getById":"دریافت صفحه خانه",
    "HomePageControllerImpl.getAllTypes":"دریافت لیست انواع صفحه خانه",
    "HomePageControllerImpl.getAllDestinations":"دریافت همه مقصد های صفحه خانه",
    "PlaceGymControllerImpl.setDefaultMultimedia":"ثبت تصویر اصلی برای یک مجموعه",
    "PlaceGymControllerImpl.updateOrder":"تغییر اولویت نمایش یک مجموعه",
    "CorporateControllerImpl.getCorporateInviteCode":"دریافت کدعصویت یک سازمان",
    "ReportControllerImpl.ticketBuyCountThisWeek":"دریافت گزارش خرید هفته",
    "PlaceCateringControllerImpl.update":"به روز رسانی اطلاعات یک کیترینگ",
    "TicketFoodControllerImpl.query":"دریافت لیست آیتم های یک کیترینگ",
    "PlaceCateringControllerImpl.getBuyableByPlace":"دریافت فروشی های یک مرکز",
    "ReportControllerImpl.getActivePersonnel":"دریافت گزارش کاربران فعال",
    "SmsControllerImpl.add":"افزودت دستی یک پیامک",
    "ReportControllerImpl.getActiveInEnterPlacePersonnel":"دریافت گزارش ورود کاربران فعال",
    "ReportControllerImpl.getBalanceChangedReport":"دریافت گزارش تغیرات حساب",
    "ReportControllerImpl.getAiReport":"دریافت گزارش هوش مصنوعی",
    "NoteControllerImpl.update":"بروزرسانی یک یادداشت",
    "CorporateControllerImpl.delete":"حذف یک شرکت",
    "PlaceRateControllerImpl.add":"ثبت امتیاز برای یک مجموعه",
    "PlaceCateringControllerImpl.changeStatus":"تغییر وضعیت یک کیترینگ",
    "TicketFoodMenuControllerImpl.copyDate":"منو کیترینگ کپی از یک روز دیگر",
    "SportControllerImpl.delete":"حذف یک ورزش",
    "InvoiceControllerImpl.addFood":"افزودن یک غذا به فاکتور",
    "PlacePersonnelControllerImpl.getCateringPersonnelByUser":"دریافت پرسنل کیترینگ",
    "TicketFoodMenuControllerImpl.add":"افزودن یک منو به کیترینگ",
    "InvoiceControllerImpl.sendOrderToCatering":"ارسال سفارش به کیترینگ",
    "InvoiceControllerImpl.sendOrderToCorporate":"ارسال سفارش غذا به سازمان",
    "WsControllerImpl.getSessionList":"دریافت سشن های فعال",
    "WsControllerImpl.query":"دریافت چت های گذشته",
    "PurchasedSubscribeControllerImpl.exitUserOfPlace":"ثبت خروج از مجموعه",
    "PlaceCateringControllerImpl.add":"افزودن یک کیترینگ",
    "NotificationSubscriptionControllerImpl.add":"درخواست دریافت نوتیفیکیشن",
    "TicketSubscribeControllerImpl.query":"دریافت لیست بلیط ها",
    "FinanceSettlementUserDepositControllerImpl.getAllCreditors":"دریافت لیست کیف پول ها",
    "SettingControllerImpl.getCallList":"دریافت لیست تماس ها",
    "SettingControllerImpl.callToNumber":"تماس با یک شماره",
    "TicketSubscribeControllerImpl.addSubscribeActiveTimes": "افزودن زمان فعالیت به عضویت",
    "TicketCourseControllerImpl.getTicketCourseByPlace":"دریافت لیست کلاس های یک مجموعه",
    "PlaceAboutControllerImpl.getAllAboutByPlaces":"دریافت قوانین و مقررات مجموعه",
    "PurchasedSubscribeControllerImpl.getUserSubscribesByPlace": "دریافت بلیط های خریداری شده از مجموعه",
    "TicketSubscribeControllerImpl.getTicketSubscribeByPlace": "دریافت بلیط های یک مجموعه",
    "PlacePersonnelControllerImpl.getPersonnelByPlace": "دریافت پرسنل یک مجموعه",
    "SettingControllerImpl.DoMaximumManagedDiscount": "افزایش حد اکثری تخفیف ها",
    "ReportControllerImpl.getPopularSports":"دریافت گزارش ورزش های پر طرفدار",
    "ReportControllerImpl.getGenderCompetition":"دریافت گزارش نسبت ورزش آقایان وخانم ها",
    "PlaceSportControllerImpl.getSportsByPlace": "دریافت ورزش های یک مجموعه",
    "PlaceAboutControllerImpl.getAboutByPlace": "دریافت درباره یک مجموعه",
    "OptionOfPlaceControllerImpl.getByPlaceId": "دریافت امکانات یک مرکز",
    "PlaceQrMessageControllerImpl.getByPlace":"دریافت اطلاعات qr های یک مجموعه",
    "UserControllerImpl.getMyPlaceWallet": "دریافت اطلاعات کیف پول",
    "PlaceControllerImpl.getPlaceByUser": "دریافت مراکز یک کاربر",
    "GatewayControllerImpl.updateImage": "درگاه تغییر تصویر",
    "ActiveTimesControllerImpl.addAll": "افزودن زمان فعالیت",
    "NoteControllerImpl.getByParam": "دریافت یادداشت ها و دفتر چه تلفن",
    "PlaceControllerImpl.query": "دریافت لیست مراکز",
    "":"",
}
