export const widgetDestination=[
    "PLACES" , "SPORTS" , "OUTERBROWSER" , "INNERBROWSER" , "USERLIST" , "PROFILE" , "CONTENTS" , "DISCOUNTS" , "SINGLECONTENT" , "SINGLEDISCOUNT" , "INVITEFRIENDS" , "SURVEYLIST" , "LOGOUT"

]
