package com.notrika.gympin.domain.finance.gateways.parsian;


import java.util.HashMap;
import java.util.Map;

public class FailureMessageProvider {

    private static final Map<Short, String> messages = new HashMap<>();

    static {
        messages.put((short)-32768 ,  "خطای ناشناخته رخ داده است");
        messages.put((short)-32004 ,  "خطادر فراخوانی سرویس درخواست خرید تسهیم آفالین");
        messages.put((short)-32003 ,  "مبلغ کل با جمع مبالغ تسهیم شده برابر نمی باشد");
        messages.put((short)-32002 ,  "مبلغ دریک یا چند آیتم داده شده معتبر نمی باشد");
        messages.put((short)-32001 ,  "لیست شماره شباها خالیاست");
        messages.put((short)-32000 ,  "خطادر فراخوان یسرویس کنترل شبای ذینفعان تسهیم آفالین");
        messages.put((short)-20000 ,  "برخی از شباها معتبر نمی باشد");
        messages.put((short)-1653 ,  "شناسه الگوریتم صحیح نمی باشد");
        messages.put((short)-1652 ,  "داده ی ورودی با الگوریتم مورد نظر مطابقت ندارد");
        messages.put((short)-1651 ,  "قالب ورودی الگوریتم صحیح نیست");
        messages.put((short)-1650 ,  "داده الگوریتم خالیاست");
        messages.put((short)-1638 ,  "فراخوانی سرویس درخواست شارژ تاپ آپ ناموفق بود");
        messages.put((short)-1637 ,  "Single-Phased UD Payment SW2exception");
        messages.put((short)-1636 ,  "Single-Phased USSD Topup Charge Payment Exception");
        messages.put((short)-1635 ,  "Single-Phased USSD Sale Payment Exception");
        messages.put((short)-1634 ,  "Single-Phased USSD Bill Payment Exception");
        messages.put((short)-1633 ,  "Non of batch bill request items transaction was successful.");
        messages.put((short)-1632 ,  "No batch bill request items found to process");
        messages.put((short)-1631 ,  "Some of bill items transaction was successful.");
        messages.put((short)-1630 ,  "Failed to continue batch bill transactions, because of a not continuable status occured.");
        messages.put((short)-1629 ,  "Batch Transaction Exception.");
        messages.put((short)-1628 ,  "اندیس پیوند کارت معتبر نمی باشد");
        messages.put((short)-1627 ,  "اندیس کارت معتبر نمی باشد");
        messages.put((short)-1626 ,  "انجام تراکنش روی این درگاه مجاز نمی باشد");
        messages.put((short)-1625 ,  "تراکنشی برای درخواست انجام نشده است که قابل برگشت باشد");
        messages.put((short)-1624 ,  "شارژکارت ناموفق میباشد");
        messages.put((short)-1623 ,  "استثنای فراخوانی سرویس صادرکننده");
        messages.put((short)-1622 ,  "استثنادر کنترل محدودیت پذیرنده برای شماره کارت");
        messages.put((short)-1621 ,  "انجام تراکنش محدود به کارت های پذیرنده میباشد");
        messages.put((short)-1620 ,  "تاپ آپ در درگاه ناموفق بود. جهت رفع مغایرت با مرکز تماس به شماره021-2318تماس بگیرید");
        messages.put((short)-1619 ,  "تاپ آپ در واسط سرویس ناموفق بود. جهت رفع مغایرت با مرکز تماس به شماره021-2318تماس بگیرید");
        messages.put((short)-1618 ,  "تاپ آپ توسط تامین کننده ناموفق بود. جهت رفع مغایرت با مرکز تماس به شماره021-2318تماس بگیرید");
        messages.put((short)-1617 ,  "خطای بانک در شارژ تاپ آپ. به کد وضعیت بانک مراجعه شود");
        messages.put((short)-1616 ,  "خطا در پردازش تراکنش پرداخت با کدQR");
        messages.put((short)-1615 ,  "استثنای ناشناخته در پرداخت");
        messages.put((short)-1614 ,  "خطا در ذخیره درخواست پرداخت با کدQR");
        messages.put((short)-1613 ,  "خطا در بازیابی اطلاعات پذیرنده کتابخانه پرداخت موبایلی");
        messages.put((short)-1612 ,  "خطا در اعتبارسنجی درخواست پرداخت توسط کتابخانه پرداخت موبایلی");
        messages.put((short)-1611 ,  "اشکال در بازیابی شماره سفارش جدید");
        messages.put((short)-1610 ,  "خطای بانک در پرداخت.به کد وضعیت بانک مراجعه شود");
        messages.put((short)-1609 ,  "خطای بانک در پرداخت. به کد وضعیت بانک مراجعه شود");
        messages.put((short)-1608 ,  "خطای بانک در پرداخت قبض.به کد وضعیت بانک مراجعه شود");
        messages.put((short)-1607 ,  "اشکالدر عملیات پرداخت قبض بصورت تک فاز");
        messages.put((short)-1606 ,  "Iso Reversal failed");
        messages.put((short)-1605 ,  "Iso Advice failed");
        messages.put((short)-1604 ,  "خطا در به روز رسانی اطلاعات تراکنش ارسالی به سوئیچ بانکی");
        messages.put((short)-1603 ,  "اشکال در عملیات تراکنش موبایل خرید سرویس پرداخت");
        messages.put((short)-1602 ,  "اشکال در عملیات تراکنش موبایل قبض سرویس پرداخت");
        messages.put((short)-1601 ,  "اشکال در عملیات تراکنش موبایل خریدسرویس پرداخت");
        messages.put((short)-1600 ,  "اشکال در عملیات تراکنش شارژ تاپ آپ سرویس پرداخت");
        messages.put((short)-1599 ,  "اشکال در عملیات تراکنش اینترنتی قبض سرویس پرداخت");
        messages.put((short)-1598 ,  "اشکال در عملیات تراکنش اینترنتی خریدسرویس پرداخت");
        messages.put((short)-1597 ,  "اشکال در عملیات بازیابی اطالعات تراکنش تاپ آپ سرویس پرداخت");
        messages.put((short)-1596 ,  "اشکال در عملیات بازیابی اطالعات تراکنش قبض سرویس پرداخت");
        messages.put((short)-1595 ,  "اشکال در عملیات بازیابی اطالعات تراکنش خریدسرویس پرداخت");
        messages.put((short)-1594 ,  "اشکال در عملیات بازیابی اطالعات تراکنش تاپ آپ ام پیال");
        messages.put((short)-1593 ,  "اشکال در عملیات بازیابی اطالعات تراکنش قبض ام پیال");
        messages.put((short)-1592 ,  "اشکال در عملیات بازیابی اطالعات تراکنش خریدام پیال");
        messages.put((short)-1591 ,  "توکنکارت معتبر نمی باشد");
        messages.put((short)-1590 ,  "شماره موبایلشارژ شونده معتبر نمی باشد");
        messages.put((short)-1589 ,  "نقضقالب مقدار عددی");
        messages.put((short)-1588 ,  "IsoWrapper.DoTransaction failure in TransactionRule");
        messages.put((short)-1587 ,  "اطالعات درخواست پرداخت در منطق تراکنش یافت نشد");
        messages.put((short)-1586 ,  "خطادر تبدیلپاسخ ایزوبه خروجیBusinessRule");
        messages.put((short)-1585 ,  "عملیات برگشت تراکنش در سرویسبرگشت تراکنش ناموفق بود");
        messages.put((short)-1584 ,  "اشکال در عملیات تراکنش موبایل خریدMPL");
        messages.put((short)-1583 ,  "اشکال در عملیات تراکنش موبایلقبضMPL");
        messages.put((short)-1582 ,  "اشکال در عملیات تراکنش موبایلخریدMPL");
        messages.put((short)-1581 ,  "اشکال در عملیات تراکنش شارژ تاپ آپMPL");
        messages.put((short)-1580 ,  "اشکال در عملیات تراکنش اینترنتیقبضMPL");
        messages.put((short)-1579 ,  "اشکال در عملیات تراکنش اینترنتیخریدMPL");
        messages.put((short)-1578 ,  "فراخوانیسرویسدرخواستخریدUDناموفق بود");
        messages.put((short)-1577 ,  "اشکالدر عملیات خریدشارژ تاپ آپ بصورت تک فاز");
        messages.put((short)-1576 ,  "اشکالدر عملیات خریدبصورت تک فاز");
        messages.put((short)-1575 ,  "صفحهدرگاه در کالینتبارگزاریشد");
        messages.put((short)-1574 ,  "خطادر اجرایمتد ایندکسصفحه پرداخت");
        messages.put((short)-1573 ,  "پساز اجرای متد ایندکس صفحه پرداخت");
        messages.put((short)-1572 ,  "پیشاز اجرایمتد ایندکسصفحه پرداخت");
        messages.put((short)-1571 ,  "اشکالدر بارگذاریصفحه پرداخت");
        messages.put((short)-1570 ,  "فرآیندپرداخت در صفحه درگاه پرداخت با اشکالیمواجه شد");
        messages.put((short)-1569 ,  "کاپچامعتبر نبود");
        messages.put((short)-1568 ,  "مدلصفحه پرداخت معتبر نبود");
        messages.put((short)-1567 ,  "پرداختقبض داده شده به دلیلمحدودیتامکانپذیرنمی باشد");
        messages.put((short)-1566 ,  "SinglePhasedPayment_TransactionResponseIsNotValid");
        messages.put((short)-1565 ,  "SinglePhasedBillPayment_Exception");
        messages.put((short)-1564 ,  "اشکالدر عملیات پرداخت تک فاز");
        messages.put((short)-1563 ,  "تمامیپرداخت ها ناموفق میباشد");
        messages.put((short)-1562 ,  "بخشیاز قبوض پرداخت شده و بخشیدچار مشکل شده است");
        messages.put((short)-1561 ,  "تاییدهتراکنش ناموفق میباشد-مشکلیدر سیستمرخ داده لطفامجددا تالش نمایید");
        messages.put((short)-1560 ,  "صفحهدرگاه پرداخت بارگذاریشد");
        messages.put((short)-1555 ,  "هیچیکاز قبوض داده شده معتبر نبود. وضعیتقبوض را بررسینمایید");
        messages.put((short)-1554 ,  "تعدادیاز قبوض داده شده پذیرششد. وضعیتقبوض را بررسینمایید");
        messages.put((short)-1553 ,  "خطادر درج درخواست قبض گروهی");
        messages.put((short)-1552 ,  "برگشتتراکنش مجاز نمی باشد");
        messages.put((short)-1551 ,  "برگشتتراکنش قبال ً انجام شده است");
        messages.put((short)-1550 ,  "برگشتتراکنش در وضعیتجاریامکان پذیرنمی باشد");
        messages.put((short)-1549 ,  "زمانمجاز برایدرخواست برگشت تراکنش به اتمام رسیدهاست");
        messages.put((short)-1548 ,  "فراخوانیسرویسدرخواست پرداخت قبض ناموفق بود");
        messages.put((short)-1547 ,  "تراکنشبرگشت به سوئیچارسال شد");
        messages.put((short)-1546 ,  "تراکنشبرگشت در انتظار برایارسال به سوئیچاست");
        messages.put((short)-1545 ,  "درجوضعیتتراکنش پیشاز ارسال تراکنش تاییدیهناموفق بود");
        messages.put((short)-1544 ,  "تراکنشتاییدیهبا موفقیتبه سوئیچارسال شد");
        messages.put((short)-1543 ,  "درجوضعیتتراکنش پیشاز ارسال تراکنش تاییدیهناموفق بود");
        messages.put((short)-1542 ,  "تراکنشتاییدیهدر انتظار برایارسال است");
        messages.put((short)-1541 ,  "درجوضعیتانجام تراکنش در سوئیچناموفق میباشد");
        messages.put((short)-1540 ,  "تاییدتراکنش ناموفق می باشد");
        messages.put((short)-1539 ,  "Payment is not successful to advice.");
        messages.put((short)-1538 ,  "ValidateBeforeConfirm failed");
        messages.put((short)-1537 ,  "An error occured in BeforeSaveRequest");
        messages.put((short)-1536 ,  "فراخوانیسرویسدرخواست شارژ تاپ آپ ناموفق بود");
        messages.put((short)-1535 ,  "درج نشانگر تأیید تراکنش موفق، موفقیت آمیز نبود");
        messages.put((short)-1534 ,  "Successful Audit Time was not found.");
        messages.put((short)-1533 ,  "تراکنشقبال ً تاییدشده است");
        messages.put((short)-1532 ,  "تراکنشاز سویپذیرندهتاییدشد");
        messages.put((short)-1531 ,  "تاییدتراکنش ناموفق امکان پذیرنمی باشد");
        messages.put((short)-1530 ,  "پذیرندهمجاز به تاییداینتراکنش نمی باشد");
        messages.put((short)-1529 ,  "بازیابی اطالعات پرداخت برایتاییدتراکنش ناموفق بود");
        messages.put((short)-1528 ,  "اطالعاتپرداختیافتنشد");
        messages.put((short)-1527 ,  "انجامعملیات درخواست پرداخت تراکنش خریدناموفق بود");
        messages.put((short)-1526 ,  "درج مرحله پایان پرداخت ناموفق می باشد");
        messages.put((short)-1525 ,  "EndPayment");
        messages.put((short)-1524 ,  "درجاطالعات پرداخت بیمهپارسیانناموفق بود");
        messages.put((short)-1523 ,  "پردازشفرآیندانجام تراکنش ناموفق میباشد");
        messages.put((short)-1522 ,  "Unable to find PaymentSwitchConfig record for current transaction request.");
        messages.put((short)-1521 ,  "Iso Creation failed.");
        messages.put((short)-1520 ,  "درجمرحله آماده بودن تراکنش برایارسال به سویچناموفق میباشد");
        messages.put((short)-1519 ,  "تراکنشآماده ارسال به سوئیچمیباشد");
        messages.put((short)-1518 ,  "درج مرحله شروع پرداخت ناموفق می باشد");
        messages.put((short)-1517 ,  "کاربر دکمه پرداخت را فشرده است");
        messages.put((short)-1516 ,  "درج اطالعات تراکنش پرداخت ناموفق میباشد");
        messages.put((short)-1515 ,  "درج اطالعات درخواست پرداخت ناموفق میباشد");
        messages.put((short)-1514 ,  "درج مرحله بارگذاریصفحه درگاه پرداخت ناموفق میباشد");
        messages.put((short)-1513 ,  "درج مرحله ارسال تراکنش برگشت به سویچ ناموفق میباشد");
        messages.put((short)-1512 ,  "درج مرحله ارسال تراکنش تاییدهبه سویج ناموفق میباشد");
        messages.put((short)-1511 ,  "درج مرحله درخواست تاییدتراکنش ناموفق میباشد");
        messages.put((short)-1510 ,  "درج مرحله ارجاع به سایت پذیرنده ناموفق میباشد");
        messages.put((short)-1509 ,  "درج مرحله ارسال تراکنش به سویچ ناموفق میباشد");
        messages.put((short)-1508 ,  "درجمرحله ثبت درخواست اولیه پرداخت ناموفق میباشد");
        messages.put((short)-1507 ,  "تراکنش برگشت به سوئیچ ارسال شد");
        messages.put((short)-1506 ,  "تراکنش تاییدیه به سوئیچ ارسال شد");
        messages.put((short)-1505 ,  "تایید تراکنش توسط پذیرنده انجام شد");
        messages.put((short)-1504 ,  "درگاه پرداخت اینترنتی صفحه پرداخت را به پذیرنده ارجاع داد");
        messages.put((short)-1503 ,  "تراکنش پرداخت به سوئیچ ارسال شد");
        messages.put((short)-1502 ,  "کاربروارد صفحه درگاه پرداخت اینترتی شد");
        messages.put((short)-1500 ,  "ثبتاولیهدرخواست");
        messages.put((short)-1006 ,  "Can not get ISO Response Code from Message");
        messages.put((short)-1005 ,  "Iso Response Parse Error");
        messages.put((short)-1004 ,  "طول داده دریافتی از سوئیچ نامعتبر است");
        messages.put((short)-1003 ,  "خطادر انجام تراکنش رویسوئیچ");
        messages.put((short)-1002 ,  "خطادر ارسال اطالعات به سوئیچ");
        messages.put((short)-1001 ,  "خطادر اتصال ویا دریافت اطالعات از سوئیچNetwork Timeout");
        messages.put((short)-1000 ,  "خطادر دریافت اطالعات از سوئیچ");
        messages.put((short)-501 ,  "خطادر برقراریارتباط شبکه ایبا دیتابیس");
        messages.put((short)-500 ,  "خطادر درج اطالعات");
        messages.put((short)-155 ,  "اجازه پرداخت تک فاز اعطا نشده است");
        messages.put((short)-154 ,  "Either Card Number or Card Index parameters must be specified.");
        messages.put((short)-153 ,  "قالب شناسه حساب صحیح نمی باشد");
        messages.put((short)-152 ,  "عدموجود شناسه حساب در داده اضافی");
        messages.put((short)-148 ,  "پارامتر ورودی معتبر نمی باشد");
        messages.put((short)-147 ,  "نوع شارژ معتبر نمی باشد");
        messages.put((short)-146 ,  "شماره موبایل برای شارژ معتبر نمی باشد");
        messages.put((short)-145 ,  "اقالم تسهیم تعیین نشده است");
        messages.put((short)-144 ,  "مبلغ در برخی از اقالم معتبر نمی باشد");
        messages.put((short)-143 ,  "جمع مبالغ تسهیم با مبلغ تراکنش مغایرت دارد");
        messages.put((short)-142 ,  "شناسه قبض یاپرداخت معتبر نمی باشد");
        messages.put((short)-141 ,  "طول رمز دوم معتبر نمی باشد");
        messages.put((short)-140 ,  "رمزدوم معتبر نمی باشد");
        messages.put((short)-139 ,  "کدامنیتی وارد شده صحیح نمی باش");
        messages.put((short)-138 ,  "عملیات  پرداخت توسط کاربر لغو شد");
        messages.put((short)-137 ,  "DelegateCode does not end with CheckDigit.");
        messages.put((short)-136 ,  "DelegateCode length is less than or equal to CheckDigit.");
        messages.put((short)-135 ,  "CheckDigitمعتبر نمی باشد");
        messages.put((short)-134 ,  "DelegatePassمعتبر نمی باشد");
        messages.put((short)-133 ,  "DelegateCodeمعتبر نمی باشد");
        messages.put((short)-132 ,  "مبلغ تراکنش کمتر از حداقل مجاز میباشد");
        messages.put((short)-131 ,  "Tokenنامعتبر میباشد");
        messages.put((short)-130 ,  "توکنمنقضیشده است");
        messages.put((short)-129 ,  "قالب داده ورودی صحیح نمی باشد");
        messages.put((short)-128 ,  "قالب آدرس IPمعتبر نمی باشد");
        messages.put((short)-127 ,  "آدرس اینترنتی معتبر نمی باشد");
        messages.put((short)-126 ,  "کدشناسایی پذیرنده معتبر نمی باشد");
        messages.put((short)-125 ,  "کدCVV2صحیح نمی باشد");
        messages.put((short)-124 ,  "لطفا فیلد رمز اینترنتی کارت را کامل کنید");
        messages.put((short)-123 ,  "تاریخ انقضای کارت معتبر نمی باشد");
        messages.put((short)-122 ,  "شماره کارت معتبر نمی باشد");
        messages.put((short)-121 ,  "رشته داده شده بطور کامل عددی نمی باشد");
        messages.put((short)-120 ,  "طول داده ورودی معتبر نمی باشد");
        messages.put((short)-119 ,  "سازمان نامعتبر می باشد");
        messages.put((short)-118 ,  "مقدارارسال شده عدد نمی باشد");
        messages.put((short)-117 ,  "طول رشته کم تر از حد مجاز می باشد");
        messages.put((short)-116 ,  "طول رشته بیشاز حد مجاز می باشد");
        messages.put((short)-115 ,  "شناسه پرداخت نامعتبر می باشد");
        messages.put((short)-114 ,  "شناسه قبض نامعتبر می باشد");
        messages.put((short)-113 ,  "پارامتر ورودی خالی می باشد");
        messages.put((short)-112 ,  "شناسه سفارش تکراری است");
        messages.put((short)-111 ,  "مبلغ تراکنش بیش از حد مجاز پذیرنده می باشد");
        messages.put((short)-110 ,  "قابلیتOCPبرایپذیرنده غیرفعال می باشد");
        messages.put((short)-109 ,  "قابلیت پرداخت خرید کالای ایرانی برای پذیرنده غیرفعال می باشد");
        messages.put((short)-108 ,  "قابلیت برگشت تراکنش برای پذیرنده غیرفعال می باشد");
        messages.put((short)-107 ,  "قابلیت ارسال تاییده تراکنش برای پذیرنده غیرفعال می باشد");
        messages.put((short)-106 ,  "قابلیت شارژ برایپذیرنده غیرفعال می باشد");
        messages.put((short)-105 ,  "قابلیت تاپ آپ برایپذیرنده غیرفعال می باشد");
        messages.put((short)-104 ,  "قابلیت پرداخت قبض برایپذیرنده غیرفعال می باشد");
        messages.put((short)-103 ,  "قابلیت خرید برایپذیرنده غیرفعال می باشد");
        messages.put((short)-102 ,  "تراکنش با موفقیت برگشت داده شد");
        messages.put((short)-101 ,  "پذیرنده اهراز هویت نشد");
        messages.put((short)-100 ,  "پذیرنده غیرفعال می باشد");
        messages.put((short)-1 ,  "خطای سرور");
        messages.put((short)0 ,  "موفق");
        messages.put((short)1 ,  "صادرکننده یکارت از انجام تراکنش صرف نظر کرد");
        messages.put((short)2 ,  "عملیات تاییدیه اینتراکنش قبلا باموفقیت صورت پذیرفته است");
        messages.put((short)3 ,  "پذیرنده ی فروشگاهی نامعتبر میباشد");
        messages.put((short)4 ,  "کارت توسط دستگاه ضبط شود");
        messages.put((short)5 ,  "ازانجام تراکنش صرف نظر شد");
        messages.put((short)6 ,  "بروز خطایی ناشناخته");
        messages.put((short)7 ,  "به دلیل شرایط خاص کارت توسط دستگاه ضبط شود");
        messages.put((short)8 ,  "با تشخیص هویت دارنده یکارت، تراکنش موفق می باشد");
        messages.put((short)9 ,  "درخواست رسیده در حال پی گیری و انجام است");
        messages.put((short)10 ,  "تراکنش با مبلغی پایین تر از مبلغ درخواستی ( کمبود پول ATM یا حساب مشتری ) پذیرفته شده است");
        messages.put((short)11 ,  "تراکنش با وجود احتمالی برخی مشکالت پذیرفته شده است ( به علت چایگاه مشتریVIP)");
        messages.put((short)12 ,  "تراکنش نامعتبر است");
        messages.put((short)13 ,  "مبلغ تراکنش اصالحیه نادرست است");
        messages.put((short)14 ,  "شماره کارت ارسالی نامعتبر است (وجود ندارد)");
        messages.put((short)15 ,  "صادرکنندهی کارت نامعتبراست (وجود ندارد)");
        messages.put((short)16 ,  "تراکن شمورد تاییداست و اطلاعات شیار سوم کارت به روز رسانی شود");
        messages.put((short)17 ,  "مشتری درخواست کننده حذف شده است");
        messages.put((short)18 ,  "درمواقعی که یک تراکنش به هر دلیل پذیرفته نشده است و یا با شرایط خاصی پذیرفته شده است در صورت تایید و یا سماجت مشتری این پیغام راخواهیم داشتپ");
        messages.put((short)19 ,  "تراکنش مجددا ارسال شود");
        messages.put((short)20 ,  "درموقعیتی که سوئیچ جهت پذیرش تراکنش نیازمند پرس و جو از کارت است ممکن است درخواست از کارت ( ترمینال) بنماید این پیام مبین نامعتبر بودن جواب است");
        messages.put((short)21 ,  "درصورتی که پاسخ به در خواست ترمینال نیازمند هیچ پاسخ خاص یا عملکردی نباشیم این پیام را خواهیم داشت");
        messages.put((short)22 ,  "تراکنش مشکوک به بد عمل کردن ( کارت ، ترمینال ، دارنده کارت ) بوده است لذا پذیرفته نشده است");
        messages.put((short)23 ,  "کارمزدارسالی پذیرنده غیرقابل قبول است");
        messages.put((short)24 ,  "زمانیکه یک تراکنش نیازمند عمل کرد یا فراخوانی فایلی خاص باشد و فایل مذکرو در مبدا درخواست موجود نباشد این پیام را خواهیم داشت");
        messages.put((short)25 ,  "تراکنش اصلی یافت نشد");
        messages.put((short)26 ,  "عملیات فایل تکراری");
        messages.put((short)27 ,  "خطادر اصالح فیلد اطالعاتی");
        messages.put((short)28 ,  "فایل مورد نظر lock شده است");
        messages.put((short)29 ,  "عملیات فایل ناموفق");
        messages.put((short)30 ,  "قالب پیام دارای اشکال است");
        messages.put((short)31 ,  "پذیرنده توسط سوئیچ پشتیبانی نمیشود");
        messages.put((short)32 ,  "تراکنش به صورت غیر قطعی کامل شده است ( به عنوان مثال تراکنش سپرده گزاری که از دید مشتری کامل شده است ولی می بایست تکمیل گردد");
        messages.put((short)33 ,  "تاریخ انقضای کارت سپری شده است. کارت توسط دستگاه ضبط شود");
        messages.put((short)34 ,  "تراکنش اصلی باموفقیت انجام نپذیرفته است");
        messages.put((short)35 ,  "بنا بر توصیه موسسه یا بانک مدیر کارت به پذیرنده کارت ضبط شده است");
        messages.put((short)36 ,  "کارت محدود شده است. کارت توسط دستگاه ضبط شود");
        messages.put((short)37 ,  "پذیرنده در نتیجه چنین درخواستی با بخش امنیتی موسسه یا بانک مدیر کارت تماس گرفته است ( یا میگیرد )");
        messages.put((short)38 ,  "تعداد دفعات ورود رمز غلط بیش از حدمجاز است. کارت توسط دستگاه ضبط شود");
        messages.put((short)39 ,  "کارت حساب اعتباری ندارد");
        messages.put((short)40 ,  "عملیات درخواستی پشتیبانی نمی گردد");
        messages.put((short)41 ,  "کارت مفقودی می باشد. کارت توسط دستگاه ضبط شود");
        messages.put((short)42 ,  "کارت حساب عمومی ندارد");
        messages.put((short)43 ,  "کارت مسروقه می باشد. کارت توسط دستگاه ضبط شود");
        messages.put((short)44 ,  "کارت حساب سرمایه گذاری ندارد");
        messages.put((short)45 ,  "قبض قابل پرداخت نمی باشد");
        messages.put((short)51 ,  "موجودی کافی نمی باشد");
        messages.put((short)52 ,  "کارت حساب جاری ندارد");
        messages.put((short)53 ,  "کارتحساب قرض الحسنه ندارد");
        messages.put((short)54 ,  "تاریخ انقضای کارت سپری شده است");
        messages.put((short)55 ,  "رمزکارت نا معتبر است");
        messages.put((short)56 ,  "کارت نا معتبر است");
        messages.put((short)57 ,  "انجام تراکنش مربوطه توسط دارنده ی کارت مجاز نمی باشد");
        messages.put((short)58 ,  "انجام تراکنش مربوطه توسط پایانه ی انجام دهنده مجاز نمی باشد");
        messages.put((short)59 ,  "کارت مظنون به تقلب است");
        messages.put((short)60 ,  "بنا بر توصیه موسسه یا بانک مدیر کارت به پذیرنده کارت ، تراکنش درخواستی پذیرفته نمی شود");
        messages.put((short)61 ,  "مبلغ تراکنش کمتر از حد تعیین شده توسط صادر کننده کارت و یا بیشتراز حد مجاز می باشد");
        messages.put((short)62 ,  "کارت محدود شده است");
        messages.put((short)63 ,  "تمهیدات امنیتی نقض گردیده است");
        messages.put((short)64 ,  "مبلغ تراکنش اصلی نامعتبر است. (تراکنش مالی اصلی با این مبلغ نمی باشد)");
        messages.put((short)65 ,  "تعداد درخواست تراکنش بیش از حد مجاز می باشد");
        messages.put((short)66 ,  "درپی تراکنش درخواستی پذیرنده با بخش امنیتی موسسه یا بانک تماس گرفته است ( و یا میگیرد )");
        messages.put((short)67 ,  "کارتتوسط دستگاه ضبط شود");
        messages.put((short)68 ,  "پاسخ الزم برای تکمیل یا انجام تراکنش خیلی دیر رسیده است");
        messages.put((short)69 ,  "تعداد دفعات تکرار رمز از حد مجاز گذشته است");
        messages.put((short)75 ,  "تعداد دفعات ورود رمز غلط بیش از حد مجاز است");
        messages.put((short)76 ,  "مبلغ انتقال داده شده معتبر نیست");
        messages.put((short)77 ,  "روز مالی تراکنش نا معتبر است یا مهلت زمان ارسال اصالاحیه به پایان رسیده است");
        messages.put((short)78 ,  "کارت فعال نیست");
        messages.put((short)79 ,  "حساب متصل به کارت نا معتبر است یا دارای اشکال است");
        messages.put((short)80 ,  "درخواست تراکنش رد شده است");
        messages.put((short)81 ,  "کارت پذیرفته نشد ( اختصاصیSLM)");
        messages.put((short)82 ,  "پیام تایید از دستگاه خود پرداز دریافت نشده است ( اختصاصیSLm)");
        messages.put((short)83 ,  "سرویسگر سوئیچ کارت تراکنش را نپذیرفته است");
        messages.put((short)84 ,  "درتراکنشهایی که انجام آن مستلزم ارتباط با صادر کننده است در صورت فعال نبودن صادر کننده این پیام در پاسخ ارسال خواهد شد");
        messages.put((short)85 ,  "پردازشگر و یا مبدا انجام تراکنش معتبر نیست");
        messages.put((short)86 ,  "تراکنش درخواستی برای بخش سخت افزاری درخواست شده از آن قابل قبول نیست");
        messages.put((short)87 ,  "سیستم در تبادل کلید رمز دچار مشکل شده است ( کد پاسخ اختصاصیSLM)");
        messages.put((short)88 ,  "سیستم در تبادل کلید MAC دچار مشکل شده است (کد پاسخ اختصاصیSLM)");
        messages.put((short)89 ,  "عدم تایید تراکنش توسط سوئیچ خارجی ( کد پاسخ اختصاصیSLM)");
        messages.put((short)90 ,  "سامانه مقصد تراکنش درحال انجام عملیات پایان روز می باشد");
        messages.put((short)91 ,  "سیستم صدور مجوز انجام تراکنش موقتا غیر فعال است و یا زمان تعیین شده برای صدو مجوز به پایان رسیده است");
        messages.put((short)92 ,  "مقصد تراکنش پیدا نشد");
        messages.put((short)93 ,  "امکان تکمیل تراکنش وجود ندارد");
        messages.put((short)94 ,  "ارسال تکراری تراکنش بوجود آمده است");
        messages.put((short)95 ,  "درعملیات مغایرت گیری ترمینال اشکال رخ داده است");
        messages.put((short)96 ,  "اشکال در عملکرد سیستم");
        messages.put((short)97 ,  "تراکنش از سوی صادر کننده کارت رد شده است");
        messages.put((short)99 ,  "خطای صادر کنندگی");
        messages.put((short)200 ,  "سایر خطاهای نگاشت نشده سامانه های بانکی");
        messages.put((short)-300,"تایید تراکنش با خطا مواجه شد. در صورتی که مبلغ از حساب شما کسر شده، مبلغ کسر شده، حداکثر تا 72 ساعت به حساب باز می‌گردد");
        messages.put((short)-310,"خطا در عملیات با پشتیبانی جیم‌پین تماس بگیرید. کد پیگیری خطا : ");
        messages.put((short)-311,"تراکنش یافت نشد، کد پیگیری تراکنش : ");
        messages.put((short)-312,"پرداخت‌کننده شناسایی نشد. کد پیگیری تراکنش : ");
        messages.put((short)-313,"تراکنش قبلاً محاسبه و مبلغ آن به حساب شما واریز شده. کد پیگیری تراکنش : ");
    }

    public static String getMessage(Short code) {
        return messages.getOrDefault(code,
                "خطا در تکمیل خرید. در صورتی که مبلغ از حساب شما کسر شده، مبلغ کسر شده، حداکثر تا 72 ساعت به حساب باز می‌گردد");
    }
}
