package com.notrika.gympin.common.finance.serial.enums;

public enum ProcessTypeEnum {
    CASH_IN_ACCOUNT_CHARGE_CORPORATE,
    CASH_IN_ACCOUNT_CHARGE_USER,
    CASH_OUT_GYMPIN,
    CASH_OUT_PLACE,
    CASH_OUT_CORPORATE,
    CASH_OUT_PERSONAL,
    TRA_INCREASE_PERSONNEL_CREDIT_SINGLE,
    TRA_INCREASE_PERSONNEL_CREDIT_GIFT,
    TRA_INCREASE_PERSONNEL_CREDIT_MULTIPLE,
    TRA_INCREASE_PERSONNEL_CREDIT_NW_MULTIPLE,
    TRA_DECREASE_PERSONNEL_CREDIT_SINGLE,
    TRA_DECREASE_PERSONNEL_CREDIT_MULTIPLE,
    TRA_EXPIRE_PERSONNEL_CREDIT_MANUAL,
    TRA_EXPIRE_PERSONNEL_CREDIT_SYSTEM,
    TRA_REMOVE_CORPORATE_PERSONNEL,
    TRA_CHECKOUT_BASKET,
    TRA_CHECKOUT_BASKET_CORPORATE,
    TRA_USE_TICKET,
    TRA_USER_WALLETS,
    TRA_REFUND_TICKET,
    NOT_DEFINE
}
