package com.notrika.gympin.common.transaction.enums;

public enum TransactionType {
    CHARGE_CORPORATE,
    CHARGE_USER,
    CHARGE_PLACE,
    GIFT,
    PERSONNEL_USE_CREDIT,
    CORPORATE_PERSONNEL_USE_CREDIT,
    CORPORATE_PERSONNEL_ADD_CREDIT,
    USER_USE_BALANCE,
    PLACE_TICKET_SETTLEMENT,
    PLACE_SETTLEMENT,
    COMMISSION
}
