package com.notrika.gympin.common.transaction.enums;

public enum TransactionType {
    CHARGE_CORPORATE,CHARGE_USER,CHARGE_PLACE,GIFT,PERSONNEL_USE_CREDIT,CORPORATE_PERSONNEL_USE_CREDIT,USER_USE_BALANCE,PLACE_SETTLEMENT,COMMISSION
}
