//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.11 at 11:59:48 AM IRST 
//


package com.notrika.gympin.common.finance.gateway.AutoGenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ConfirmPaymentWithAddDataResult" type="{https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService}ClientConfirmResponseDataAddData" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "confirmPaymentWithAddDataResult"
})
@XmlRootElement(name = "ConfirmPaymentWithAddDataResponse", namespace = "https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")
public class ConfirmPaymentWithAddDataResponse {

    @XmlElement(name = "ConfirmPaymentWithAddDataResult", namespace = "https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")
    protected ClientConfirmResponseDataAddData confirmPaymentWithAddDataResult;

    /**
     * Gets the value of the confirmPaymentWithAddDataResult property.
     * 
     * @return
     *     possible object is
     *     {@link ClientConfirmResponseDataAddData }
     *     
     */
    public ClientConfirmResponseDataAddData getConfirmPaymentWithAddDataResult() {
        return confirmPaymentWithAddDataResult;
    }

    /**
     * Sets the value of the confirmPaymentWithAddDataResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientConfirmResponseDataAddData }
     *     
     */
    public void setConfirmPaymentWithAddDataResult(ClientConfirmResponseDataAddData value) {
        this.confirmPaymentWithAddDataResult = value;
    }

}
