//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.10.24 at 12:04:05 AM GMT+03:30
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.notrika.gympin.common.finance.gateway.AutoGenerated;
