//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.11 at 11:59:48 AM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.notrika.gympin.common.finance.gateway.AutoGenerated;
