//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.05 at 09:15:49 PM IRST 
//


package com.notrika.gympin.common.finance.gateway.AutoGenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UDSalePaymentRequestResult" type="{https://pec.Shaparak.ir/NewIPGServices/Sale/SaleService}ClientPaymentResponseDataBase" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "udSalePaymentRequestResult"
})
@XmlRootElement(name = "UDSalePaymentRequestResponse")
public class UDSalePaymentRequestResponse {

    @XmlElement(name = "UDSalePaymentRequestResult")
    protected ClientPaymentResponseDataBase udSalePaymentRequestResult;

    /**
     * Gets the value of the udSalePaymentRequestResult property.
     * 
     * @return
     *     possible object is
     *     {@link ClientPaymentResponseDataBase }
     *     
     */
    public ClientPaymentResponseDataBase getUDSalePaymentRequestResult() {
        return udSalePaymentRequestResult;
    }

    /**
     * Sets the value of the udSalePaymentRequestResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientPaymentResponseDataBase }
     *     
     */
    public void setUDSalePaymentRequestResult(ClientPaymentResponseDataBase value) {
        this.udSalePaymentRequestResult = value;
    }

}
